modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="kiritossword"
version="1.0.0"
displayName="KiritosSword"
description="Adds the KiritosSword item to your game."
authors="WolfofAstora"

[[dependencies.kiritossword]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.kiritossword]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
